### ISSUE TITLE
ComodIDE not showing up in Protege 5.2.0

### ISSUE THREAD

**Issue by syntheticperson** [comodide/comodide.github.io#1]
I downloaded CoModIDE-1.1.0.jar and copied into my protege plugin folder.
It shows up in the plugins dialog, but not in the windows/tab.
What am I missing?
<img width="1007" alt="Screen Shot 2020-05-30 at 10 22 34 AM" src="https://user-images.githubusercontent.com/119148/83335209-ed985e00-a25f-11ea-9d33-e20275e40765.png">
<img width="469" alt="Screen Shot 2020-05-30 at 10 22 44 AM" src="https://user-images.githubusercontent.com/119148/83335213-f721c600-a25f-11ea-98ee-025c31469361.png">

**Comment by syntheticperson** [comment]
I downloaded and installed the newest Protege 5.5.0, and CoModIDE-1.1.0 works with that version of Protege!

**Comment by hammar** [comment]
Nice to hear you got it working! Note that there are A LOT of bugs in 1.1.0. We’re releasing 1.1.1 with a bunch of fixes in 1-2 days. Or you could download and build the master branch which has most fixes already.

**Comment by syntheticperson** [comment]
Thanks for developing ComodIDE. I've been waiting for a visual way to authoring ontologies for a very long time.

**Comment by syntheticperson** [comment]
What are the build instructions? I am noticing buggy behavior, and am interested in trying your newest code.

**Comment by syntheticperson** [comment]
I'm not seeing source code in this repo:  
https://github.com/comodide/comodide.github.io
Is there a different repo with the code?

**Comment by syntheticperson** [comment]
Never mind, I was looking in the wrong repo, found it here:
https://github.com/comodide/CoModIDE/tree/master

**Comment by hammar** [comment]
Yes, that's the right repo. Apparently our GitHub-hosted webpage links to the source for that webpage, not the CoModIDE plugin itself. Stupid mistake on our part, I'll make sure to rectify it as soon as possible.

To build just do `mvn clean package` and copy the jar from the target directory into the Protégé plugins directory.

**Comment by syntheticperson** [comment]
No problem. What IDE are you using? XCode, Eclipse, or other?
Thanks

**Comment by hammar** [comment]
I'm using Eclipse, but I think @cogan-shimizu-wsu may be using something else (the indentation is a tell).

**Comment by syntheticperson** [comment]
Good to know. Haha! Thanks

**Comment by syntheticperson** [comment]
I have Eclipse 2020 installed, and I imported ComodIDE as a maven project.
How do you build using Maven from within Eclipse?

**Comment by syntheticperson** [comment]
I tried selecting the pom.xml, right mouse Run As Maven Build..., but don't know what to set the goals to.
<img width="986" alt="Screen Shot 2020-05-30 at 3 26 59 PM" src="https://user-images.githubusercontent.com/119148/83340232-74fac700-a28a-11ea-90d3-9012c37ec7a7.png">

**Comment by hammar** [comment]
In that box, type `package`.

**Comment by syntheticperson** [comment]
That worked!
Thanks
Where can I see a list of the bugs fixed in the current code?

**Comment by hammar** [comment]
https://github.com/comodide/CoModIDE/milestone/1?closed=1
